# Gate and operator OpenQASM standard names
GATE_CH: str = 'ch'
GATE_CR: str = 'cu3'
GATE_CRX: str = 'crx'
GATE_CRY: str = 'cry'
GATE_CRZ: str = 'crz'
GATE_CS: str = 'cs'
GATE_CSDG: str = 'csdg'
GATE_CX: str = 'cx'
GATE_CY: str = 'cy'
GATE_CZ: str = 'cz'
GATE_H: str = 'h'
GATE_ID: str = 'id'
GATE_R: str = 'u'
GATE_RX: str = 'rx'
GATE_RY: str = 'ry'
GATE_RZ: str = 'rz'
GATE_S: str = 's'
GATE_SDG: str = 'sdg'
GATE_SX: str = 'sx'
GATE_T: str = 't'
GATE_TDG: str = 'tdg'
GATE_TOFFOLI: str = 'ccx'
GATE_X: str = 'x'
GATE_Y: str = 'y'
GATE_Z: str = 'z'

# Backend quantum processor's parameters and constants
BACK_WMIQSIM_NAME = 'QiskitSimulator'
BACK_WMIQSIM_VERSION = '1.0.0'
BACK_WMIQSIM_URL = 'https://wmiqc-api.wmi.badw.de/1/qiskitSimulator'
BACK_WMIQC_NAME = 'WMIQC'
BACK_WMIQC_VERSION = '1.0.0'

# Qobj parameters and constants
QOBJ_ID_QISM_EXPERIMENT = 'WMI_QiskitSim_Experiment'
QOBJ_SCHEMA_VERSION = '1.0'